### ISSUE TITLE
Are triggers added automatically ?

### ISSUE THREAD

**Issue by harijay** [linuxlewis/djorm-ext-pgfulltext#14]
Hi I am a postgres newbie. Is there a mailing list or irc channel to discus this extension.
Does this extension add triggers to postgres to handle updates or is that handled elsewhere within python code?
I have a model with "title", "post" , "tags_array" and I created the ts_vector type using south. But I messed up my migrations . I was wondering if it is possible to know which fields went into a ts_vector? i.e is there a way using psql command line to tell whether the ts_vector has only "title" and "post" or whether it also includes "tags_array".

Sorry to send these questions in as issues and please let me know where I can ask them instead.

**Comment by naro** [comment]
@pepade84 Your link is dead (404). Would it be possible to put relevant solution here if you can find it? Thank you.

**Comment by naro** [comment]
Just for the records: https://web.archive.org/web/20141102042927/http://bogdan-ivanov.com/entry/full-text-search-postgresql-and-django

**Comment by ptrdtznr** [comment]
or this one here: 
http://tech.swamps.io/full-text-search-using-postgresql-and-django/
