### ISSUE TITLE
Does it support Trigram matching?

### ISSUE THREAD

**Issue by chogarcia** [linuxlewis/djorm-ext-pgfulltext#44]
In particular it can help to recognize misspelled input words that will not be matched directly by the full text search mechanism.

[pg_trgm Text Search Integration from PostgreSQL documentation](http://www.postgresql.org/docs/9.3/static/pgtrgm.html#AEN152967)

**Comment by rvanlaar** [comment]
@cho-is You closed this issue, did you get it to work? 

I haven't yet.

**Comment by chogarcia** [comment]
I had lots problems with this so I gave up finally. I am using watson now.
