### ISSUE TITLE
Pypi versions

### ISSUE THREAD

**Issue by gsong** [linuxlewis/djorm-ext-pgfulltext#62]
Why are 0.9.2 and 0.9.3 later than 0.10 and incorporate more stuff?

**Comment by ryokamiya** [comment]
I also ran into the same issue when I installed the latest (0.10) where missing management commands, i.e. update_search_field. The issue was resolved when I reinstall it with "djorm-ext-pgfulltext==0.9.3"

**Comment by gsong** [comment]
This package is no longer relevant for recent Django.
